# Generated by Django 4.1.7 on 2023-04-27 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название мероприятия', max_length=50, verbose_name='Название')),
                ('desctiption', models.TextField(blank=True, help_text='Описание мероприятия', null=True, verbose_name='Описание')),
                ('logo', models.ImageField(help_text='Логотип мероприятия', max_length=50, upload_to='images/', verbose_name='Логотип')),
                ('status_event', models.CharField(choices=[('1', 'Не началось'), ('2', 'В процессе'), ('3', 'Закончилось')], default='1', help_text='Статус мероприятия', max_length=1)),
                ('data_start', models.DateField(help_text='Дата начала мероприятия', null=True, verbose_name='Дата начала')),
                ('data_end', models.DateField(help_text='Дата конца мероприятия', null=True, verbose_name='Дата конца')),
                ('city', models.TextField(help_text='Город проведения мероприятия', max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-status_event', '-data_start', '-data_end'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Роль человека на мероприятии', max_length=50, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(help_text='Фамилия пользователя', max_length=50, verbose_name='Фамилия')),
                ('age', models.IntegerField(help_text='Полных лет пользователя', null=True, verbose_name='Возраст')),
                ('city', models.CharField(help_text='Город, в котором живет пользователь', max_length=50, verbose_name='Город')),
                ('sex', models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский')], default='M', help_text='Пол пользователя', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UsersEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reg', models.DateField(help_text='Дата регистрации на меропрятии', null=True, verbose_name='Дата регистрации')),
                ('link_certificate', models.FileField(help_text='Сертификат участника мероприятия', null=True, upload_to='', verbose_name='Сертификат')),
                ('rating', models.IntegerField(help_text='Занимеемое место на мероприятии', null=True, verbose_name='Занимеемое место')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.status')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.users')),
            ],
            options={
                'verbose_name': 'Событие и участник',
                'verbose_name_plural': 'События и участники',
                'ordering': ['-id_status', '-date_reg', '-rating'],
            },
        ),
    ]
