# Generated by Django 4.1.7 on 2023-04-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='second_name',
            field=models.CharField(help_text='Отчество пользователя', max_length=50, verbose_name='Фамилия'),
        ),
    ]
